name: Build Stamp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go mod tidy
      - run: mkdir -p build && go build -o build/stamp main.go
      - uses: actions/upload-artifact@v4
        with:
          name: stamp
          path: build/
