name: Release Stamp

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - run: go mod tidy

      - name: Build binaries
        run: |
          mkdir -p dist
          for GOOS in linux windows darwin; do
            for GOARCH in amd64 arm64; do
              if [ "$GOOS" = "windows" ] && [ "$GOARCH" = "arm64" ]; then continue; fi
              EXT=$([ "$GOOS" = "windows" ] && echo ".exe" || echo "")
              GOOS=$GOOS GOARCH=$GOARCH go build -o dist/stamp-${GOOS}-${GOARCH}${EXT} main.go
            done
          done

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
